# Generated by Django 2.2 on 2019-04-04 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hashTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filehash', models.CharField(max_length=50, unique=True)),
                ('shareddate', models.DateField(default=datetime.date.today)),
                ('lastuseddate', models.DateField(default=datetime.date.today)),
                ('size', models.IntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='peer',
            fields=[
                ('peer_ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Ratings', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='refTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadswithpeer', models.IntegerField()),
                ('filehash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_sharing.hashTable')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_sharing.peer')),
            ],
        ),
        migrations.AddField(
            model_name='hashtable',
            name='peer_id',
            field=models.ManyToManyField(through='file_sharing.refTable', to='file_sharing.peer'),
        ),
    ]
